MLFLOW:
  MLFLOW_TRACKING_URI: http://127.0.0.1:15000
  MLFLOW_TRACKING_USERNAME: mlflow
  MLFLOW_TRACKING_PASSWORD: ***
S3:
  AWS_ACCESS_KEY_ID: ***
  AWS_SECRET_ACCESS_KEY: ***
  MLFLOW_S3_ENDPOINT_URL: http://127.0.0.1:19000
LOCAL_ENV:
  MLFLOW_ENV_TYPE: dev
  MLFLOW_FILL_EMPTY_UPLOAD_FILES: '1'
  MLFLOW_VALIDATE_FILES: checksum
  MLFLOW_DST_PATH: /srv/dev/mlflow/examples/attribution_model/destination
  MLFLOW_IGNORE_PATH: /srv/dev/mlflow/examples/attribution_model/.mlflowignore
  no_proxy: localhost,127.0.0.1
