version: '3.3'

services:
    db:
        restart: always
        image: postgres:13.1
        container_name: mlflow_db
        expose:
            - "5432"
        networks:
            - backend
        environment:
            POSTGRES_DB: ${POSTGRES_DB:-mlflow}
            POSTGRES_USER: ${POSTGRES_USER:-postgres}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres_pw}
        volumes:
            - ./postgres/data:/var/lib/postgresql/data

    minio:
        restart: always
        image: minio/minio:RELEASE.2021-03-01T04-20-55Z
        container_name: mlflow_minio
        environment:
            - MINIO_ROOT_USER=${AWS_ACCESS_KEY_ID:-access_key}
            - MINIO_ROOT_PASSWORD=${AWS_SECRET_ACCESS_KEY:-secret_key}
        volumes:
            - ./minio/data:/data
        ports:
            - "${MINIO_PORT:-19000}:9000"
        networks:
            - backend
        command: server /data

    web:
        restart: always
        build:
            context: ./mlflow_server
            dockerfile: Dockerfile
            args:
                # Set proxy for pip
                - HTTP_PROXY=${PROXY:-}
                - HTTPS_PROXY=${PROXY:-}
        image: mlflow_server
        container_name: mlflow_server
        environment:
            - MLFLOW_S3_ENDPOINT_URL=http://minio:9000/
            - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-access_key}
            - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-secret_key}
            # ! For debugging purposes only -> Remove in production
            - PYTHONUNBUFFERED=1
        expose:
            - "5000"
        networks:
            - frontend
            - backend
        depends_on:
            - db
            - minio
        command: >
            mlflow server
                --backend-store-uri postgresql+psycopg2://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres_pw}@db:5432/${POSTGRES_DB:-mlflow}
                --default-artifact-root s3://${S3_BUCKET:-mlflow-bucket}/
                --host 0.0.0.0
                --port 5000

    nginx:
        restart: always
        build: ./nginx
        image: mlflow_nginx
        container_name: mlflow_nginx
        ports:
            - "${MLFLOW_PORT:-15000}:80"
        networks:
            - frontend
        depends_on:
            - web

networks:
    frontend:
        driver: bridge
    backend:
        driver: bridge
